# question_data = [{"category": "Sports", "type": "multiple", "difficulty": "easy",
#                   "question": "Which of the following sports is not part of the triathlon?",
#                   "correct_answer": "Horse-Riding", "incorrect_answers": ["Cycling", "Swimming", "Running"]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "hard",
#                   "question": "How many times did Martina Navratilova win the Wimbledon Singles Championship?",
#                   "correct_answer": "Nine", "incorrect_answers": ["Ten", "Seven", "Eight"]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "hard",
#                   "question": "Which female player won the gold medal of table tennis singles in 2016 Olympics Games?",
#                   "correct_answer": "DING Ning (China)",
#                   "incorrect_answers": ["LI Xiaoxia (China)", "Ai FUKUHARA (Japan)",
#                                         "Song KIM (North Korea)"]},
#                  {"category": "Sports", "type": "boolean", "difficulty": "medium",
#                   "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
#                   "correct_answer": "False", "incorrect_answers": ["True"]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "easy",
#                   "question": "What team won the 2016 MLS Cup?",
#                   "correct_answer": "Seattle Sounders",
#                   "incorrect_answers": ["Colorado Rapids", "Toronto FC", "Montreal Impact"]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "medium",
#                   "question": "Why was The Green Monster at Fenway Park was originally built?",
#                   "correct_answer": "To prevent viewing games from outside the park.",
#                   "incorrect_answers": ["To make getting home runs harder.", "To display advertisements.",
#                                         "To provide extra seating."]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "medium",
#                   "question": "How many French Open&#039;s did Bj&ouml;rn Borg win?",
#                   "correct_answer": "6", "incorrect_answers": ["4", "9", "2"]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "easy",
#                   "question": "Who is often called &quot;the Maestro&quot; in the men&#039;s tennis circuit?",
#                   "correct_answer": "Roger Federer",
#                   "incorrect_answers": ["Bill Tilden", "Boris Becker", "Pete Sampras"]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "easy",
#                   "question": "When was the FC Schalke 04 founded?",
#                   "correct_answer": "1904", "incorrect_answers": ["1909", "2008", "1999"]},
#                  {"category": "Sports", "type": "multiple", "difficulty": "hard",
#                   "question": "The AHL affiliate team of the Boston Bruins is named what?",
#                   "correct_answer": "Providence Bruins",
#                   "incorrect_answers": ["New Haven Bruins", "Cambridge Bruins", "Hartford Bruins"]}]

question_data = [{"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
                   "question": "A doctor with a PhD is a doctor of what?",
                  "correct_answer": "Philosophy","incorrect_answers": ["Psychology", "Phrenology", "Physical Therapy"]},
                  {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
                  "question": "What character was once considered to be the 27th letter of the alphabet?",
                  "correct_answer": "Ampersand","incorrect_answers": ["Interrobang", "Tilde", "Pilcrow"]},
                   {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
                   "question": "What direction does the Statue of Liberty face?",
                   "correct_answer": "Southeast","incorrect_answers": ["Southwest", "Northwest", "Northeast"]},
                   {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
                   "question": "What year was the RoboSapien toy robot released?",
                   "correct_answer": "2004", "incorrect_answers": ["2000", "2001", "2006"]},
                   {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
                   "question": "Which church&'s interior in Vatican City was designed in 1503 by renaissance architects including Bramante, Michelangelo and Bernini?",
                   "correct_answer": "St. Peter's Basilica","incorrect_answers": ["Catania Cathedral", "St. Mark&rsquo;s Basilica","The Duomo of Florence"]},
                   {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
                   "question": "A statue of Charles Darwin sits in what London museum?",
                   "correct_answer": "Natural History Museum","incorrect_answers": ["Tate", "British Museum", "Science Museum"]},
                    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
                    "question": "How many furlongs are there in a mile?",
                     "correct_answer": "Eight","incorrect_answers": ["Two", "Four", "Six"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "A pasodoble is a type of Italian pasta sauce.",
                     "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                     "question": "'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.' is a grammatically correct sentence.",
                     "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
                     "question": "What is the profession of Elon Musk's mom, Maye Musk?",
                     "correct_answer": "Model","incorrect_answers": ["Professor", "Biologist", "Musician"]}]
